name: Deploy Lambda Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy Lambda functions
        run: |
          for dir in lambda/*/ ; do
            if [ -d "$dir" ]; then
              echo "Deploying Lambda in folder $dir"
              cd "$dir"
              zip -r function.zip . 
              function_name=$(basename "$dir")
              aws lambda update-function-code \
                --function-name "$function_name" \
                --zip-file fileb://function.zip
              cd ../../
            fi
          done
